### ISSUE TITLE
Scrolling Toolbar

### ISSUE THREAD

**Issue by Gurchain** [mbrlabs/Lorien#116]
**Feature/enhancement description:**

When the window is resized, the toolbar can be scrolled across to use any toolbar button without overlap.

The color palette popup is misplaced in my solution and I also find the blue highlight very annoying, but I should be able to fix both of these problems. 

Current:

https://user-images.githubusercontent.com/89324754/166402462-2afec006-d3ec-4028-9b6b-3e6bdd09bdc0.mp4

Proposed:

https://user-images.githubusercontent.com/89324754/166402476-4e3d6c54-619f-4843-8a4c-c37846935cda.mp4

**Comment by mbrlabs** [comment]
This looks pretty nice! The blue highlight of the scrollbars can be changed in theme file ([theme_dark.tres](https://github.com/mbrlabs/Lorien/blob/main/lorien/UI/Themes/theme_dark.tres)). I never used scrollbars in Lorien, so i didn't bother to change it i guess.

The color selection popup is more difficult, since it assumes there is always space on the left. If there is not enough space i think it's best if it dynamically anchors it's right edge to the right edge of the brush color button of the toolbar...so basically the opposite of the current behaviour.

**Comment by Gurchain** [comment]
@mbrlabs this is my design at the moment:

https://user-images.githubusercontent.com/89324754/168936984-c1627f60-6392-4349-99bb-032ee97dba09.mp4
