### ISSUE TITLE
Add missing keys to translation, add automatic localization addition and some minor changes

### ISSUE THREAD

**Issue by Astrono2** [mbrlabs/Lorien#16]
#### I'm proposing the following changes, which, if approved, I will implement myself and make a pull request:

**Add keys for:**
- Untitled project name
- Theme names
- Anti-aliasing methods

Also, currently it seems that there is a ERROR_NOT_IMPLEMENTED key, but then in the theme selector, "(not implemented yet)" is hardcoded in english. For this, first of all there should be code for translating the OptionButtons' items. Then I think ERROR_NOT_IMPLEMENTED should be changed to a more general  NOT_IMPLEMENTED, as it would be used in places other than errors. Finally, it should be possible to have more than one space separated keys in a same string, and translate them separately. This would allow for, for example, "THEME_LIGHT NOT_IMPLEMENTED".

I think the least cumbersome way of implementing that would require a method in Utils.gd for translating strings that would, assuming that keys cannot contain spaces, translate each space separated word on it's own. This could also very easily accommodate for the use of placeholders in translations, such as "Autosave not yet implemented for (CURRENT_PROJECT_NAME)" or the such.

Finally, I would replace the manual addition of new localizations with an automated one by adding a NAME key at the top of every localization file and adding it to the language OptionButton, as well as replacing the `const LANGUAGE_ID_*`s and `const LOCALE_*`s with an array of locales created automatically at startup.

**Comment by mbrlabs** [comment]
Names and technical terms should not be translated IMO. That includes:
- Theme names
- Anti Aliasing Methods

Since we don't have a light theme yet, the best way to handle the "(not implemented yet)" in the theme name is to just remove the "Light" option for now.

> ERROR_NOT_IMPLEMENTED should be changed to a more general NOT_IMPLEMENTED

Yes, that's fine

> Finally, it should be possible to have more than one space separated keys in a same string, and translate them separately.

I'm not sure if that's worth it, since different languages can have quite different sentence structures and concatenating strings like that might not make sense for all languages. It would also only work if you use `tr()`. For Labels etc. you'd have to override some functions i guess..not sure if that's even possible. So that's overkill.

> Finally, I would replace the manual addition of new localizations with an automated one by adding a NAME ...

Yep, that's great. Not sure about `NAME` though. Maybe `LANGUAGE_NAME` is better :)

**Comment by Astrono2** [comment]
Yeah that makes a lot of sense, thanks. I'll start working on it.

**Comment by Astrono2** [comment]
#20

**Comment by mbrlabs** [comment]
Closing since implemented in #20
