### ISSUE TITLE
Menu that open dialogues should have a '...' after them

### ISSUE THREAD

**Issue by nithinshoban** [mbrlabs/Lorien#166]
**Lorien version:**
0.5.0

**OS/device including version:**
macOs 10.13.6

**Issue description:**
Nice App!

Open, Settings, Settings in menu should have a '...' after them to indicate they will show a dialogue.
Save As should have three dots

**Steps to reproduce:**

Click on the main menu (hamburger menu)

![image](https://user-images.githubusercontent.com/107873679/174639411-37dd60c3-e32e-4f86-94f5-cde915a7f943.png)

**Comment by hansemro** [comment]
Gimp dropdown for reference:
![2022-06-20_11-32](https://user-images.githubusercontent.com/40348686/174660726-dc900445-b6cc-45f6-8b30-7e1ebef692a0.png)

**Comment by mbrlabs** [comment]
As far as i know `...` should only be used when after clicking the button an immediate input action from the user is required, not just when a dialog opens. So that would exclude the `About` button, which also opens a dialog but does not require futher action (except closing it). Settings/Preferences often don't have this as well.

This is a nice article about it: https://uxdesign.cc/dot-dot-dot-7ce6170bfc7f

**Comment by mbrlabs** [comment]
So i added it to `Open`, `Save as` and `Export` in 1473b5008f3ec767d82211401f018d5fe21ef16e. No `Settings` or `About`
