### ISSUE TITLE
Convert afdesign files to an open format

### ISSUE THREAD

**Issue by MrApplejuice** [mbrlabs/Lorien#173]
The [art](https://github.com/mbrlabs/Lorien/tree/main/art) folder of the repository contains designs for the logo/icons used in the application, I think(?)

The problem is that I, as probably a lot of contributors who are not using Mac, cannot open these files. I think those are [Affinity Designer](https://affinity.serif.com/en-us/designer/) files? It would be great and welcome if someone who has access to that program could commit copies of those files which use some open standard like svg or png so that all contributors can chip in and use these design files!

**Comment by mbrlabs** [comment]
Completly understand. The problem is i absolutly can not stand Inkscape (the UX is horrible). I don't use a Mac either. Affinity Designer is also available for Windows (costs ~$50 with without any subscriptions and is very often for 50% on sale). This is probably the only software that holds me back from using Linux fulltime again.

Anyway, i will look into how good svg is an interchangeable format but i'm pretty sure some things will be lost in translation. It would probably work if every icon had it's own svg file though.

**Comment by MrApplejuice** [comment]
Clarification: I would suggest to add SVG or even PNG as an _additional_ format only. I understand the value of using some of the proprietary software, especially one got used to a tool and some even come with specialized features. Would just be great to have something that is _easy_ to access on _any_ system. My suggested formats would:

- be sourcable by pretty much anyone (not necessarily to use them as for editing)
- render directly here on github, so checking what is on those files becomes dead-simple :smile: 

(And yeah, I am a Linux bloke with a Windows-partition for gaming only.. :-P I _could_ fire up my Linux instance in a VM and use Affinity Designer in there, but well, for me that would be costs for a software that I would only use for this project. For now not really an investment I would prefer.)

**Comment by mbrlabs** [comment]
> be sourcable by pretty much anyone (not necessarily to use them as for editing)

Good point. I was worried having to maintain 2 different formats. But new custom icons are very rarely added, so why not. Just exported an svg from Affinity and it looks fine in Inkscape.

**Comment by mbrlabs** [comment]
I added svg versions in 9708ec0ca0bf34ac335a61b0d34427a1dfe31b75
