### ISSUE TITLE
Pressure (thickness) of lines and rectangles too thin and not configurable

### ISSUE THREAD

**Issue by goatchurchprime** [mbrlabs/Lorien#212]
There's a `const PRESSURE := 0.5` hardcoded in the RectangleTool and CircleTool, and this value itself is hardcoded as an immediate value (as 0.5) in the LineTool

This gives a default thickness for lines that is far too low in my opinion when you're mixing lines and painted drawings just to do straighter lines.

**Comment by tafode** [comment]
@goatchurchprime Since this feature has been missed by several users (see bug #252  and  #216), I have created a small prototype and wanted to ask if this would be usable for you?
https://youtu.be/qWqjiMVRzwo

@mbrlabs Would this way of configuration also be ok for you? If so, I would clean up my code a bit and create a PR.

**Comment by mbrlabs** [comment]
Hello, sorry for the delay. Yeah, this looks good!
