### ISSUE TITLE
v0.2.0 mac release unable to start (Lorien is damaged and can't be opened)

### ISSUE THREAD

**Issue by umieat** [mbrlabs/Lorien#22]
**Lorien version:**
v0.2.0

**OS/device including version:**
MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
Processor: 1,4 GHz Quad-Core Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3
Graphics: Intel Iris Plus Graphics 645 1536 MB
running BigSur 11.2.3

**Issue description:**
When opening application it fails and gives error:
Lorien is damaged and can't be opened
The app has been modified, and its code does not match the original signed code. The app may be broken or corrupted, or it may have been tampered with

**Steps to reproduce:**
Download mac release and try to open

**Comment by mbrlabs** [comment]
AFAIK this is a common problem with any unsigned application on Macs. It should work if you remove the Gatekeeper quarantine flag. If you want to read more about that, here is the Godot issue i got the solution from: https://github.com/godotengine/godot/issues/48076

The proper solution would be for me to singed and notarize Mac builds, but i don't want to do that.

**Comment by mbrlabs** [comment]
@umieat apparantly it's enough to build the project on a Mac...if i cross compile on Windows you get this error. Fortunally i have a Mac with BigSur (which i usually don't use) and made a build of the current main branch to test this. 

It would be great if you could test this build and verify that it works on your end (can't upload on Github because the dmg is too big): https://drive.google.com/file/d/1Y2Lqto0sJck35_vgQe5fBv7Nl88XOP50/view?usp=sharing.

**Comment by umieat** [comment]
Hi there,
I cloned repository and built Lorient myself when release doesn't work.
dmg file you provided still doesn't open.
This time it says:
“Lorien” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
I think this is still an issue about signing the build, but building from source works without any problems.

**Comment by mbrlabs** [comment]
Alright thanks for trying 👍   The error message changed at least. I guess it works for me because i built it myself and did not download it from the Internet. But i think you should still be able to run it if you disable Gatekepper (for the dmg) or whatever Apple uses to block programs. 

Closing this as wontfix. If i ever decide to get a developer lisence from Apple i'll let you know ;)
