### ISSUE TITLE
Shape Tools

### ISSUE THREAD

**Issue by Lord-Vlad** [mbrlabs/Lorien#52]
A tool to quickly create shapes lice rectangles or ellipses.

Usage:
1. Select the tool.
2. Click and drag. The shape gets created within your selection.

Additional keys:
Ctr → squares and circles.
Shift → create from center.

**Comment by Penguin-Roll** [comment]
Maybe being able to select and move the individual points of polygonal shapes would also be helpful for making freeform shapes (instead of independent line segments for drawing such shapes)? The user could hold Ctrl with the Selection Tool to select points instead of forms and then move things around like a normal selection or something.

**Comment by mbrlabs** [comment]
I implemented a rectangular shape tool. For now it's without key modifiers (like shift, ctrl, etc). If you want to check it out: i just pushed it to the main branch.

**Comment by lparth** [comment]
I ran into this wonderful project today but I needed a quick and dirty circle tool, so I hacked one up by looking at your rectangular shape tool. The PR is here, if anyone's interested:
https://github.com/mbrlabs/Lorien/pull/107

Cheers,
~parthi

**Comment by mbrlabs** [comment]
We now have rectangles, lines, circles and ellipses. Closing this.
